kind: Service
apiVersion: v1
metadata:
  name: back-end
spec:
  selector:
    app: back-end
    tier: backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    nodePort: 32131
    port: 80
    targetPort: 8080
