steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'University/'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'University/'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID','.']
  dir: 'University/'
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID']
  dir: 'University/'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  dir: 'University/'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - back-end
  - web=gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
